# 数据操作

In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

shape属性 --》 张量的形状和张量中的元素总数

In [6]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

改变张量的形状而不改变元素数量和元素值 --》 reshape

In [7]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

随机初始化参数值

In [14]:
torch.randn(3, 4)

tensor([[ 0.1549,  0.3628, -0.4851, -0.9859],
        [ 0.8086, -0.8177, -0.6345, -0.8965],
        [ 0.7199,  0.6158, -1.4228, -0.5023]])

元素为全0或全1

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## 运算符
**提供包含数值的python列表或嵌套列表，为张量中的每个元素进行赋值**
shape属性展示的是每个中括号中包含的元素数量【对上面shape理解的一个补充】

In [12]:
test = torch.tensor([[[1, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13]]])
print(test)
print(test.shape)

tensor([[[ 1,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]])
torch.Size([1, 3, 4])


标准运算符升级为按元素运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

计算每个元素的指数值

In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

将两个张量连结在一起

In [17]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

比较两个张量之间的元素是否相等

In [18]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

计算张量的和

In [19]:
x.sum()

tensor(66.)

## 广播机制
在某些情况下，即使张量形状不同，仍可以通过广播机制来进行运算

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片
和python数组一样：第一个元素索引为0，最后一个元素索引为-1.
切片： `[-1]`访问最后一个元素 `[1:3]`访问第二个和第三个元素

In [22]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

可以通过指定的索引将元素写入矩阵

In [23]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

元素批量替换

In [24]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存
创建一个和原张量形状相同的新张量，并赋值给原张量

In [25]:
before = id(y)
y = y + x
id(y) == before

False

In [26]:
z = torch.zeros_like(y)
print('id(z)', id(z))
z[:] = x + y
print('id(z)', id(z))

id(z) 1656152037392
id(z) 1656152037392


如果后续操作不需要用到x，可以直接覆盖x来减少内存开销

In [27]:
before = id(x)
x += y
id(x) == before

True

## 转换为其他python对象
将 张量 转换为 Numpy张量

In [28]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为python的标量

In [29]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)