# 线性代数
## 标量
标量：只有一个元素的张量

In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量
向量：一维张量（标量组成的列表）

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过下标读取向量的元素

In [4]:
x[3]

tensor(3)

## 长度、维度和形状
向量是数字数组，数组具有长度，向量同理，通过`len()`获取向量的长度

In [5]:
len(x)

4

当用张量表示向量时，可以通过`x.shape`获取向量的形状。
**形状**：列出了张量每个轴的长度（**维度**）。
对于只有一个轴的张量，形状只有一个元素。

In [6]:
x.shape

torch.Size([4])

## 矩阵
矩阵：二维张量（具有两个轴的张量）
方阵：矩阵的行数等于列数

In [7]:
a = torch.arange(20).reshape(5, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

使用下标获取矩阵中的元素

In [8]:
a[0,1]

tensor(1)

转置：`a.T` 以从左上到右下的对角线 顺序交换矩阵的行和列

In [9]:
a.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

**对称矩阵**：
* 前置条件：方阵（方阵的特殊类型）
* 定义：a的转置等于a本身。

In [10]:
b = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(b)
b.T == b

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量
张量：多维数组

In [12]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的本质性质
两个相同的张量（维度相同的数组）。任何二元运算的结果都是相同形状的张量。

In [23]:
a = torch.arange(20, dtype=torch.float32).reshape(5, 4)
b = a.clone()
a, a + b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [14]:
a*b

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

In [21]:
z = 2
x = torch.arange(24).reshape(2, 3, 4)
z + x, z * x, (z * x).shape, z - x, z / x, z ** x

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]),
 tensor([[[  2,   1,   0,  -1],
          [ -2,  -3,  -4,  -5],
          [ -6,  -7,  -8,  -9]],
 
         [[-10, -11, -12, -13],
          [-14, -15, -16, -17],
          [-18, -19, -20, -21]]]),
 tensor([[[   inf, 2.0000, 1.0000, 0.6667],
          [0.5000, 0.4000, 0.3333, 0.2857],
          [0.2500, 0.2222, 0.2000, 0.1818]],
 
         [[0.1667, 0.1538, 0.1429, 0.1333],
          [0.1250, 0.1176, 0.1111, 0.1053],
          [0.1000, 0.0952, 0.0909, 0.0870]]]),
 tensor([[[      1,       2,       4,       8],
          [     16,      32,      64,     128],
          [    256,     512,    1024,    2048]],
 
         [[  

## 降维
计算张量的和：把张量中所有的元素相加。
降为的体现在于 当前张量为5行4列的数组 当求和后 就变为了标量。

In [44]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [24]:
a.shape, a.sum()

(torch.Size([5, 4]), tensor(190.))

上边提到 张量 降为 标量
下面可以指定`axios`属性，降为指定轴的向量。

In [26]:
a_sum0 = a.sum(axis=0)  # 将列元素相加
a, a_sum0, a_sum0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

In [27]:
a_sum1 = a.sum(axis=1) # 将行元素相加
a, a_sum1, a_sum1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

沿着行和列对张量求和 == 张量求和

In [28]:
a.sum(axis=[0, 1])

tensor(190.)

平均值： `x.mean()` 等同于 `x.sum() / x.numel()` 
`x.numel()` 等于张量的元素总数。

In [30]:
a.mean(), a.numel(), a.sum() / a.numel()

(tensor(9.5000), 20, tensor(9.5000))

计算平均值函数也可沿指定轴 降低张量的维度

In [32]:
# 列相加 / 列元素数量
(a.mean(axis=0), a.sum(axis=0) / a.shape[0], 
 # 行相加 / 行元素数量
 a.mean(axis=1), a.sum(axis=1) / a.shape[1])

(tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]))

## 非降为求和
计算和操作不会导致张量降维。

In [34]:
print(a.sum(axis=1))
sum_a = a.sum(axis=1, keepdims=True) # keepdims 保留张量原有的维度
sum_a

tensor([ 6., 22., 38., 54., 70.])


tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

以广播的形式 a / sum_a 不会对 a 进行降为

In [35]:
a / sum_a

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

沿行或列累积总和，不降低张量维度， 可以使用`cumsum`函数。

In [41]:
a, a.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

## 点积
相同位置的元素相乘，然后求和。

In [45]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [46]:
torch.sum(x * y) # 向量相乘 后 相加 = 点积

tensor(6.)

## 矩阵--向量积
保证矩阵的行数等于向量的长度。一一对应相乘后相加。

In [47]:
a, x, torch.mv(a, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵 -- 矩阵乘法
张量a的行的和乘以张量b的列相加。

In [51]:
'''
[[ 6*1,  6*1,  6*1],(0 + 1 + 2 + 3 = 6)
 [22*1, 22*1, 22*1],(4 + 5 + 6 + 7 = 22)
 [38*1, 38*1, 38*1],
 [54*1, 54*1, 54*1],
 [70*1, 70*1, 70*1]]
'''
b = torch.ones(4, 3)
(a, b, torch.mm(a, b))

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

## 范数
L2范数：平方和开方

In [52]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L1范数：绝对值之和

In [53]:
torch.abs(u).sum()

tensor(7.)

Lp范数: p次方之和开方

In [55]:
print(torch.ones((4, 9)))
'''
√9 = 3
[[3,3,3,3]]
9*4=36
√36 = 6
'''
torch.norm(torch.ones((4, 9)))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


tensor(6.)

In [57]:
torch.norm(torch.tensor([[2.0,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]]))

tensor(8.)

## 范数和目标
没看懂